language: node_js
dist: trusty
sudo: required
before_install:
- sudo add-apt-repository ppa:avacariu/git-crypt -y
- sudo apt-get --allow-unauthenticated update -qq
- sudo apt-get --allow-unauthenticated install -qq git-crypt
- openssl aes-256-cbc -K $encrypted_589c6aae0ca0_key -iv $encrypted_589c6aae0ca0_iv -in test.key.enc -out test.key -d
script:
- git checkout -- package-lock.json
- git-crypt unlock test.key
- npm run test:all
after_success: npm run coverage
node_js:
- '8'
